

mqtt:
  broker: 
    # Test broker
    address: tcp://localhost:1883
    protocol: mqtt
    username:
    password:
    clientId: guest
    
    
    
    timeout:
      completion: 30000
      disconnection: 5000
      connection: 30
      
  topic:
    
    receiveLightMeasurement: smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured
    
    turnOn: smartylighting/streetlights/1/0/action/{streetlightId}/turn/on
    
    turnOff: smartylighting/streetlights/1/0/action/{streetlightId}/turn/off
    
    dimLight: smartylighting/streetlights/1/0/action/{streetlightId}/dim
    
